# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ThermalScanDialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ThermalScanDialog(object):
    def setupUi(self, ThermalScanDialog):
        ThermalScanDialog.setObjectName("ThermalScanDialog")
        ThermalScanDialog.resize(646, 477)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(ThermalScanDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mainLayout = QtWidgets.QVBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.ImageLayout = QtWidgets.QVBoxLayout()
        self.ImageLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.ImageLayout.setObjectName("ImageLayout")
        self.horizontalLayout_ = QtWidgets.QHBoxLayout()
        self.horizontalLayout_.setObjectName("horizontalLayout_")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(ThermalScanDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.list_images = QtWidgets.QListWidget(ThermalScanDialog)
        self.list_images.setObjectName("list_images")
        self.verticalLayout.addWidget(self.list_images)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(ThermalScanDialog)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.sb_maxTemp = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sb_maxTemp.setDecimals(1)
        self.sb_maxTemp.setMinimum(-1000.0)
        self.sb_maxTemp.setMaximum(1000.0)
        self.sb_maxTemp.setObjectName("sb_maxTemp")
        self.gridLayout.addWidget(self.sb_maxTemp, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.sb_minTemp = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sb_minTemp.setDecimals(1)
        self.sb_minTemp.setMinimum(-1001.0)
        self.sb_minTemp.setMaximum(1001.0)
        self.sb_minTemp.setObjectName("sb_minTemp")
        self.gridLayout.addWidget(self.sb_minTemp, 0, 1, 1, 1)
        self.pb_auto = QtWidgets.QPushButton(self.groupBox)
        self.pb_auto.setObjectName("pb_auto")
        self.gridLayout.addWidget(self.pb_auto, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_.addLayout(self.verticalLayout)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_21 = QtWidgets.QLabel(ThermalScanDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_21.addWidget(self.label_21)
        self.mainImage = QtWidgets.QLabel(ThermalScanDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainImage.sizePolicy().hasHeightForWidth())
        self.mainImage.setSizePolicy(sizePolicy)
        self.mainImage.setMinimumSize(QtCore.QSize(1, 1))
        self.mainImage.setMouseTracking(True)
        self.mainImage.setAcceptDrops(True)
        self.mainImage.setAutoFillBackground(True)
        self.mainImage.setFrameShape(QtWidgets.QFrame.Box)
        self.mainImage.setText("")
        self.mainImage.setAlignment(QtCore.Qt.AlignCenter)
        self.mainImage.setObjectName("mainImage")
        self.verticalLayout_21.addWidget(self.mainImage)
        self.verticalLayout_21.setStretch(1, 1)
        self.horizontalLayout_.addLayout(self.verticalLayout_21)
        self.horizontalLayout_.setStretch(0, 1)
        self.horizontalLayout_.setStretch(1, 4)
        self.ImageLayout.addLayout(self.horizontalLayout_)
        self.mainLayout.addLayout(self.ImageLayout)
        self.ButotnsLayout = QtWidgets.QHBoxLayout()
        self.ButotnsLayout.setObjectName("ButotnsLayout")
        self.pushButton_Analyze = QtWidgets.QPushButton(ThermalScanDialog)
        self.pushButton_Analyze.setEnabled(False)
        self.pushButton_Analyze.setObjectName("pushButton_Analyze")
        self.ButotnsLayout.addWidget(self.pushButton_Analyze)
        self.pushButton_Calibrate = QtWidgets.QPushButton(ThermalScanDialog)
        self.pushButton_Calibrate.setEnabled(False)
        self.pushButton_Calibrate.setObjectName("pushButton_Calibrate")
        self.ButotnsLayout.addWidget(self.pushButton_Calibrate)
        self.pushButton_Scan = QtWidgets.QPushButton(ThermalScanDialog)
        self.pushButton_Scan.setObjectName("pushButton_Scan")
        self.ButotnsLayout.addWidget(self.pushButton_Scan)
        self.pushButton_Settings = QtWidgets.QPushButton(ThermalScanDialog)
        self.pushButton_Settings.setObjectName("pushButton_Settings")
        self.ButotnsLayout.addWidget(self.pushButton_Settings)
        self.pushButton_Close = QtWidgets.QPushButton(ThermalScanDialog)
        self.pushButton_Close.setObjectName("pushButton_Close")
        self.ButotnsLayout.addWidget(self.pushButton_Close)
        self.mainLayout.addLayout(self.ButotnsLayout)
        self.mainLayout.setStretch(0, 10)
        self.verticalLayout_4.addLayout(self.mainLayout)
        self.verticalLayout_4.setStretch(0, 10)

        self.retranslateUi(ThermalScanDialog)
        QtCore.QMetaObject.connectSlotsByName(ThermalScanDialog)

    def retranslateUi(self, ThermalScanDialog):
        _translate = QtCore.QCoreApplication.translate
        ThermalScanDialog.setWindowTitle(_translate("ThermalScanDialog", "Thermal Scanner"))
        self.label.setText(_translate("ThermalScanDialog", "Scanned images"))
        self.groupBox.setTitle(_translate("ThermalScanDialog", "Colors (celsius)"))
        self.label_2.setText(_translate("ThermalScanDialog", "Max temp"))
        self.label_3.setText(_translate("ThermalScanDialog", "Min temp"))
        self.pb_auto.setText(_translate("ThermalScanDialog", "Auto"))
        self.label_21.setText(_translate("ThermalScanDialog", "Image"))
        self.pushButton_Analyze.setText(_translate("ThermalScanDialog", "Analyze"))
        self.pushButton_Calibrate.setText(_translate("ThermalScanDialog", "Calibrate"))
        self.pushButton_Scan.setText(_translate("ThermalScanDialog", "Scan"))
        self.pushButton_Settings.setText(_translate("ThermalScanDialog", "Settings..."))
        self.pushButton_Close.setText(_translate("ThermalScanDialog", "Close"))

